### ISSUE TITLE
How to change domain/hostname?

### ISSUE THREAD

**Issue by danpolanco** [sb-minimal/docker-ubuntu-open-exchange#2]
Google didn't help and it's probably simple to do.

When I try to use the twitter app, for example, it directs to twitter correctly but the redirect back to the server tries to use https://localhost...... I assume there is some easy way to tell OX my server is actually at https://ox.servername.com.

Thoughts?

**Comment by sb-minimal** [comment]
I dont use the twitter app, so i can't tell for sure, but did you try to set up a custom twitter app, as described in http://oxpedia.org/wiki/index.php?title=Twitter_Bundles
Maybe that helps?

**Comment by danpolanco** [comment]
Hmm. Interesting. I haven't. Before I close the issue, do you know if this is related:

![screen shot 2015-12-20 at 2 29 04 pm](https://cloud.githubusercontent.com/assets/3826143/11920221/1c0b43a4-a726-11e5-94bf-13e9439c048b.png)
